name: location_tagger_app
description: Add a location tag under any picture using custom coordinates.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  geocoding: ^3.0.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
